export type { IconComponent, IconlyIconProps } from "./types"
export { IconlyDocument } from "./document-outline"
export { IconlyDocumentFilled } from "./document-filled"
export { IconlyCategory } from "./category-outline"
export { IconlyCategoryFilled } from "./category-filled"
export { IconlyDiscovery } from "./discovery-outline"
export { IconlyDiscoveryFilled } from "./discovery-filled"
export { IconlyChart } from "./chart-outline"
export { IconlyChartFilled } from "./chart-filled"
export { IconlySearch } from "./search-outline"
export { IconlySearchFilled } from "./search-filled"
export { IconlyMenu } from "./menu-outline"
export { IconlyNotification } from "./notification-outline"
export { IconlyTarget } from "./target-filled"
export { IconlyClipboardCheck } from "./clipboard-check-filled"
export { IconlyFlame } from "./flame-filled"
export { IconlyTime } from "./time-filled"
